Numpy (Numerical Python) 

NumPy (short for Numerical Python) is a powerful library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.


- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.



Numpy vs Python Sequences

Python Lists:
- Flexible and versatile.
- Can store mixed data types.
- Use for general-purpose tasks when performance and memory are not critical.

Key Features:
- Flexible: Can store different data types (e.g., [1, "apple", 3.14]).
- Dynamic: You can easily add or remove elements.
- Built-in: No need to import anything; it's part of core Python.

When to Use:
- General-purpose: When you need a simple, flexible way to store and manipulate a collection of items.
- Mixed data types: When your collection includes different types of data (e.g., integers, strings).

Python Arrays:
- Homogeneous and less flexible.
- Use for memory-efficient storage of same-type elements, but less common than lists and NumPy arrays.

Key Features Array:
- Homogeneous: All elements must be of the same type (e.g., all integers or all floats).
- Less flexible: More rigid in terms of data types compared to lists.
- Less commonly used: Not as widely adopted as lists or NumPy arrays.

NumPy Arrays:
- Efficient, powerful, and designed for numerical computing.
- Use for large-scale numerical data processing, scientific computing, and when performance matters.

Key Features Numpy:

Homogeneous: All elements must be of the same type, just like Python arrays.
- Highly efficient: Faster and more memory-efficient than Python lists, especially for large datasets.
- Rich functionality: Supports complex mathematical operations, multi-dimensional arrays, broadcasting, etc.
- Multi-dimensional: Can easily handle 1D, 2D, and even n-dimensional arrays (e.g., vectors, matrices, tensors).

When to Use:
- Numerical computations: When working with large datasets or performing mathematical operations. 
- Performance: When you need speed and memory efficiency for array operations.
- Data science & machine learning: When you're working with data analysis, machine learning, or scientific computing.

- scalar = single value (1D)
- vector = group of list or list (2D)
- matrix = Rows and columns (3D)
- Tensors = Multidimensional array or data (8d,5d more)

### Creating Numpy Arrays

In [1]:
import numpy as np

arr = np.array([23,45,666])
#print(arr)
print(type(arr))

<class 'numpy.ndarray'>


In [23]:
mult = np.array([[[[54,65,34,76],
                 [56,45,767,21],
                 [23,54,12,57],
                 [23,6,7,2]]]])
mult.ndim

4

In [26]:
mult.size

16

In [27]:
mult.shape

(1, 1, 4, 4)

In [33]:
arr2 = np.array([23,0,67],dtype=complex )
arr2

array([23.+0.j,  0.+0.j, 67.+0.j])

In [35]:
l1 = np.arange(2,24)
print(l1)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [66]:
a2 = np.array([
               [[23, 23, 12],   # First block, first row
                [ 2,  6,  7],   # First block, second row
                [23,  6,  4]],  # First block, third row

               [[14, 15, 16],   # Second block, first row
                [17, 18, 19],   # Second block, second row
                [20, 21, 22]]   # Second block, third row
              ])

a2
a2.ndim
a2.shape

#----------------------------------------------------------------------------
a5 = np.array([[[23,32,53],
              [23,52,12],
              [23,53,32]]])
a5.size
a5.ndim

a5.shape



(2, 3, 3)

In [87]:
#reshape
#reshaping existing array
a5 = np.array([[[23,32,53,2],
              [23,52,12,2],
              [23,53,32,2]]])


rea5 = a5.reshape((1,6,2))
rea5


#--------------------
# creating array using reshape
a = np.arange(1,17).reshape(4,4)
print(a)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [89]:
#np.ones and np.zeroes

np.ones((3,3))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
#np.random

np.random.random((2,24))
np.random.randint(2,24,size=(2,6)) #with size 

array([[18, 22,  2, 13,  8,  5],
       [15, 16, 23, 19, 23, 13]])

In [107]:
#linspace = linearly seprable

np.linspace(2,12,6,dtype='int')



array([ 2,  4,  6,  8, 10, 12])

In [108]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
#itemsize
a5.itemsize

4

In [112]:
#dtype
a5.dtype

dtype('int32')

### Slicing and Indexing

In [1]:
import numpy as np

In [2]:
a1 = np.array([12,32,54,65,12])



a2 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])




a3 = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]]])

In [3]:
a1[-4:-1]

array([32, 54, 65])

In [4]:
a2[:,0::4]

array([[ 1,  5],
       [ 6, 10]])

In [5]:
a2[1,2]

8

In [6]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12).reshape(3,4)

a4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a6 = np.vstack((a4,a5))

In [9]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a3

dtype('int16')

### fancy indexing


In [12]:
a3[0,[0,2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [19]:
a3 = np.dtype('int16')

In [27]:
a3 = np.arange(12,dtype='int8').reshape(4,3)
a3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int8)

In [51]:
a3[:,[0,2]]
#a3[:, [0, 1]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]], dtype=int8)

In [32]:
thrd = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

In [33]:
thrd.shape

(2, 3, 4)

In [75]:
thrd[:,[0,2]]

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [21, 22, 23, 24]]])

### Boolean Indexing

In [77]:
ron = np.random.randint(1,80,24).reshape(6,4)
ron

array([[73, 35,  5, 31],
       [54, 11, 18, 26],
       [71,  9, 38, 68],
       [13, 31, 74, 34],
       [ 6, 75, 62,  6],
       [28, 62, 39, 78]])

In [87]:
ron[ron>50] # this is called boolean indexing

array([73, 54, 71, 68, 74, 75, 62, 62, 78])

In [89]:
#let's find even numbers

ron[ron % 2 == 0]

array([54, 18, 26, 38, 68, 74, 34,  6, 62,  6, 28, 62, 78])

In [96]:
for i in np.nditer(ron):
   if i %2 == 0:
    print(i,end=' ')

54 18 26 38 68 74 34 6 62 6 28 62 78 

In [98]:
#two condition greater than 50 and even numbers
ron[(ron>50) & (ron % 2 ==0)] #& is a bitwise operator

array([54, 68, 74, 62, 62, 78])

In [103]:
#numbers is not divisible by 7
ron[~(ron %7 == 0)]

array([73,  5, 31, 54, 11, 18, 26, 71,  9, 38, 68, 13, 31, 74, 34,  6, 75,
       62,  6, 62, 39, 78])